package com.crazytrends.expensemanager.appBase.utils;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class Constants {
    public static final String APP_DB_NAME = "dailyExpenseManager.db";
    public static int CAT_TYPE_All = 0;
    public static final String CAT_TYPE_BUSINESS = "Business";
    public static final String CAT_TYPE_CLOTHING = "Clothing";
    public static final String CAT_TYPE_DRINKS = "Drinks";
    public static final String CAT_TYPE_EDUCATION = "Education";
    public static int CAT_TYPE_EXPENSE = 2;
    public static String CAT_TYPE_EXPENSE_NAME = "Expense";
    public static final String CAT_TYPE_FOOD = "Food";
    public static final String CAT_TYPE_FUEL = "Fuel";
    public static final String CAT_TYPE_FUN = "Fun";
    public static final String CAT_TYPE_HOSPITAL = "Hospital";
    public static final String CAT_TYPE_HOTEL = "Hotel";
    public static int CAT_TYPE_INCOME = 1;
    public static String CAT_TYPE_INCOME_NAME = "Income";
    public static final String CAT_TYPE_LOAN = "Loan";
    public static final String CAT_TYPE_MEDICAL = "Medical";
    public static final String CAT_TYPE_MERCHANDISE = "Merchandise";
    public static final String CAT_TYPE_MOVIE = "Movie";
    public static final String CAT_TYPE_OTHER = "Other";
    public static final String CAT_TYPE_PERSONAL = "Personal";
    public static final String CAT_TYPE_PETS = "Pets";
    public static final String CAT_TYPE_RESTAURANT = "Restaurant";
    public static final String CAT_TYPE_SALARY = "Salary";
    public static final String CAT_TYPE_SHOPPING = "Shopping";
    public static final String CAT_TYPE_TIPS = "Tips";
    public static final String CAT_TYPE_TRANSPORT = "Transport";
    public static final String DB_BACKUP_DIRECTORY = "ExpenseBackup";
    public static String DISCLOSURE_DIALOG_DESC = "We would like to inform you regarding the 'Consent to Collection and Use Of Data'\n\nTo backup and restore Income/Expense data into local phone, allow access to storage permission.\n\nWe store your data on your device only, we don’t store them on our server.";
    public static final SimpleDateFormat FILE_DATE_FORMAT = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
    public static final String MODE_TYPE_CASH = "Cash";
    public static final String MODE_TYPE_CHEQUE = "Cheque";
    public static final String MODE_TYPE_CREDIT_CARD = "Credit Card";
    public static final String MODE_TYPE_DEBIT_CARD = "Debit Card";
    public static final String MODE_TYPE_NET_BANKING = "Net Banking";
    public static String PRIVACY_POLICY_URL = "https://crazytrendsapp.blogspot.com/";
    public static final String REPORT_DIRECTORY = "ExpenseReports";
    public static final int REQUEST_CODE_SIGN_IN = 1005;
    public static final int REQUEST_PERM_FILE = 1053;
    public static final SimpleDateFormat SIMPLE_DATE_FORMAT_HEADER = new SimpleDateFormat("MMMM yyyy");
    public static int SORT_TYPE_ALL = 1;
    public static int SORT_TYPE_BETWEEN_DATES = 7;
    public static int SORT_TYPE_LAST_MONTH = 6;
    public static int SORT_TYPE_LAST_WEEK = 4;
    public static int SORT_TYPE_THIS_MONTH = 5;
    public static int SORT_TYPE_TODAY = 2;
    public static int SORT_TYPE_YESTERDAY = 3;
    public static final String STATISTICS_BY_CATEGORY = "Category";
    public static final String STATISTICS_BY_MODE = "Mode";
    public static final String STATISTICS_BY_TYPE = "Type";
    public static final String showDatePatternDDMMMMYYYY = "dd/MM/yyyy";
    public static String showTimePattern = "hh:mm a";
}
